swiftmailer:
    #url: '%env(MAILER_URL)%'
    host: smtp.gmail.com
    transport: gmail
    username: fogfogtest@gmail.com
    password: testGmail159
    port: 465
    encryption: ssl
    auth_mode: login
    spool: { type: 'memory' }
