INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (1,'The Game',2018,11.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (2,'Horreur à Arkham (L''appel de Cthulu)',2006,55.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (3,'Lord of Xidit',2016,45.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (4,'Ca$h''n Gun$ Yakuzas',2006,30.00,'1 shuriken',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (5,'Ca$h''n Gun$',2008,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (6,'Photosynthesis',2018,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (7,'Abyss',2016,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (8,'La bonne paye',2016,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (9,'Cranium',2010,25.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (10,'Naufragés',2014,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (11,'Pandemic',2018,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (12,'The Lord of the Rings : The followship of the ring',2005,15.00,'2 fiches victoires',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (13,'Bang !',2018,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (14,'Code Names',2018,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (15,'Flash Point : Fire Rescue',2012,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (16,'Twin Tin Bots',2005,55.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (17,'Cortex Challenge',2015,15.00,'4 bouts de cerveau',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (18,'Taverne de la Licorne',2010,22.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (19,'Guerre froide : CIA vs KGB',2013,12.00,'manque un jeton','refaire une petite notice',NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (20,'Onk-Onk',2014,12.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (21,'rory''s story cubes',2013,12.00,'notices?',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (22,'Fluxx',2015,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (23,'Déclic!?',2013,12.00,'manque cible et regles',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (24,'Fairy Tale',NULL,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (25,'Mammboo!',2012,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (26,'Les chevaliers de la table ronde',2007,55.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (27,'Fische fluppen Frikadellen',2004,NULL,'1 bilet de 50',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (28,'Skaal',2011,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (29,'Brainstorm !',2003,45.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (30,'Dungeon Fighter',2013,35.00,NULL,NULL,'1 jeton noir');
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (31,'Dominion',2011,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (32,'Les Princes de florences',2008,60.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (33,'Imagine',2018,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (34,'Twinz',2017,15.00,'notices?',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (35,'Flick''em up!Stallion Canyon Expansion',2016,25.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (36,'7 wonders',2012,40.00,'3 merveilles',NULL,'1 merveille');
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (37,'Bazar bizarre ultime',2014,25.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (38,'Panic station',2012,315.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (39,'Les aventuriers  du rails',2017,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (40,'King of tokyo',2015,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (41,'Loups-Garous Nouvelle Lune',2014,9.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (42,'Loups-Garous Le Village',2014,45.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (43,'Red Hot Silly Dragon',2007,10.00,'1 pion,1 vert,1 rouge','2 dés remplacés',NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (44,'Perudo',2016,15.00,NULL,NULL,'1dé bleu');
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (45,'Perudo',2016,15.00,'notices',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (46,'Catane',2012,40.00,'1 fiche coup de construction',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (47,'Shadow hunter',2010,25.00,'1 cube orange remplacer par un pion en mousse',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (48,'Crimebox Inverstigation',NULL,38.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (49,'Contrées Fabuleuse',NULL,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (50,'déclic!? Family',2017,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (51,'Dobble',2016,9.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (52,'Munchkin',2016,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (53,'7 wonders cities',2013,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (54,'7 wonders leaders',2013,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (55,'MEGAWATTS',2013,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (56,'Blitz!',2015,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (57,'Senji',2010,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (58,'Mysterium',2017,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (59,'Celestia',2016,25.00,'jeton vert',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (60,'Celestia coup de pouce (rangé dans celestia)',2016,7.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (61,'Sang Rancune',2014,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (62,'Not alone',2017,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (63,'Abyss Kraken',2016,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (64,'Welcome to the dungeon',2015,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (65,'Monopoly Game of thrones',2016,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (66,'Dixit',2018,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (67,'dungeons Dragons',2005,100.00,'4 pièces remplacées.',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (68,'Polarity. The Game',2007,25.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (69,'skull',2014,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (70,'Illusio',2010,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (71,'MITO',2017,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (72,'Samurai & Katana',2005,NULL,'4 marqueur d''honneur',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (73,'Timeline',2014,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (74,'Zombicide',2014,80.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (75,'Jenga',1998,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (76,'Intrigue à Venise',1988,40.00,'tête à masque remplacé par lego + dés',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (77,'TOMB',2009,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (78,'Exploding kittens',2017,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (79,'Panique à Wall Street',2012,30.00,'1 jeton violet et 1 rouge',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (80,'Linq',2010,20.00,'notice',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (81,'Welcome back to the Dungeon',2017,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (82,'King of tokyo: Power Up',2013,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (83,'King of tokyo: Halloween',2013,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (84,'Vendredi',2012,20.00,'11 points de santé',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (85,'Gobb''it',2014,10.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (86,'Race for the Galaxy',2009,25.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (87,'Splendor',2016,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (88,'Loony Quest',2016,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (89,'Anima,Le crépuscule des dieux',2016,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (90,'Petits Meurtres et faits divers',2010,30.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (91,'Diavolo',2014,15.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (92,'Intrige',2006,20.00,'notice',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (93,'Crossing',2016,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (94,'Contrario',2013,20.00,'notice?',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (95,'Dice forge',2017,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (96,'Magic maze',2017,25.00,'1 jeton Hors-service',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (97,'Cranium Black',2009,50.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (98,'Finstere flure',2004,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (99,'Dungeon roll',2014,22.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (100,'Dominion',2009,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (101,'Puerto Rico',2011,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (102,'Ricochet Robot',2014,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (103,'Les morts aux trousses',2007,40.00,'5 supports (et 1 carton situation?)',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (104,'Stonehenge',2008,25.00,'1 barre rouge',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (105,'Stratego',2010,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (106,'Gang Rush Breakout',2017,39.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (107,'Flick''em up !',2016,65.00,'1 pion gris',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (108,'Flick''em up !',2016,65.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (109,'Diplomatie',2007,30.00,'1 pion gris',NULL,'1 pion gris');
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (110,'Space Blast',NULL,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (111,'Cité',2009,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (112,'Intrigo',2011,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (113,'Bang ! The valley of shadows',2017,10.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (114,'Himalaya',2007,45.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (115,'Carcassone',2006,70.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (116,'Illuminati',1985,NULL,'4 page de règles',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (117,'Star wars X-Wing : Le jeu de figurine',NULL,32.00,'4 barres transparentes',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (118,'Vinci : apogée et déclin des civilisations',2003,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (119,'Race for the Galaxy : Tempête en formation',2010,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (120,'Marvel Cardline',2016,25.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (121,'DUNE',1993,85.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (122,'Mah-Jong',NULL,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (123,'Bataille de fleurus',NULL,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (124,'Controverse',2001,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (125,'Anti-monopoly II',NULL,10.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (126,'Fief 2',1989,75.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (127,'Risk',1994,35.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (128,'full metal planet',1988,160.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (129,'Money Money',1989,40.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (130,'Age of ultron : Dice master',2016,20.00,'1 dé',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (131,'Loup garou',2014,12.00,'notice',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (132,'Rigor Mortis',2012,20.00,'notice',NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (133,'Start player',2017,12.00,NULL,'3 766',NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (134,'Rigor Mortis 2',2014,20.00,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (135,'Smallworld',NULL,NULL,NULL,NULL,NULL);
INSERT INTO board_game(id,name,year,price,missing,note,excess) VALUES (136,'Smallworld  extension',NULL,NULL,NULL,NULL,NULL);
